stages:
  - lint

eslint:
  stage: lint
  variables:
    NODE_VERSION: 14.17.0
  script:
    - echo "Install nvm"
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    - echo "Reload terminal"
    - . "$NVM_DIR/nvm.sh"
    - echo "Install NodeJS"
    - nvm install $NODE_VERSION
    - echo "Install dependencies"
    - npm ci
    - echo "Lint source code with ESLint"
    - npm run lint
