stages:
  - lint
  - build
  - deploy

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

.default-cache: &default-cache
  before_script:
    - npm ci --cache .npm --prefer-offline

eslint:
  extends:
    - .default-cache
  image: node:14.17.0-alpine
  stage: lint
  before_script:
    - echo "Install dependencies"
    - npm ci
  script:
    - echo "Lint source code with ESLint"
    - npm run lint

prettier:
  image: node:14.17.0-alpine
  stage: lint
  before_script:
    - echo "Install dependencies"
    - npm ci
  script:
    - echo "Format source code with Prettier"
    - npm run format

build:
  stage: build
  image: node:14.17.0-alpine
  before_script:
    - echo "Install dependencies"
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  image: ubuntu:latest
  variables:
    MAIL_USER: $MAIL_USER
    MAIL_PASS: $MAIL_PASS
  before_script:
    - apt -qq update && apt upgrade -qqy openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" | tr -d '\r' > ~/.ssh/known_hosts
    - echo "SendEnv $MAIL_PASS" >> ~/.ssh/config
    - echo "SendEnv $MAIL_USER" >> ~/.ssh/config
  script:
    - ssh -o SendEnv=MAIL_PASS $SSH_USER@$SSH_ADDRESS env
    - rsync -a --progress --human-readable ./dist $SSH_USER@$SSH_ADDRESS:~/social-network
    - rsync -a --progress --human-readable --delete --exclude-from '.gitignore' --exclude .gitignore --exclude .git --exclude test
      . $SSH_USER@$SSH_ADDRESS:~/social-network
    # use -i #SSH_PRIVATE_KEY without running ssh-add if you set this gitlab variable as a file
    - ssh $SSH_USER@$SSH_ADDRESS "pushd ~/social-network && npm ci && npm run migration:run && pm2 reload \"api\" && popd"
  dependencies: ['build']

start:
  stage: deploy
  image: ubuntu:latest
  variables:
    MAIL_USER: $MAIL_USER
    MAIL_PASS: $MAIL_PASS
  before_script:
    - apt -qq update && apt upgrade -qqy openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" | tr -d '\r' > ~/.ssh/known_hosts
    - echo "SendEnv $MAIL_PASS" >> ~/.ssh/config
    - echo "SendEnv $MAIL_USER" >> ~/.ssh/config
  script:
    - ssh $SSH_USER@$SSH_ADDRESS "pushd ~/social-network && npm ci && npm run migration:run && pm2 start npm --name \"api\" -- run "start:prod" && popd"
    - ssh -o SendEnv=MAIL_PASS -o SendEnv=MAIL_USER $SSH_USER@$SSH_ADDRESS "env | grep MAIL"
  when: manual
