stages:
  - lint

eslint:
  image: 14.17.0-alpine
  stage: lint
  script:
    - echo "Install dependencies"
    - npm ci
    - echo "Lint source code with ESLint"
    - npm run lint

prettier:
  image: 14.17.0-alpine
  stage: lint
  script:
    - echo "Install dependencies"
    - npm ci
    - echo "Format source code with Prettier"
    - npm run format
