stages:
  - lint
  - deploy

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

.default-cache: &default-cache
  before_script:
    - npm ci --cache .npm --prefer-offline

eslint:
  extends:
    - .default-cache
  image: node:14.17.0-alpine
  stage: lint
  script:
    - echo "Install dependencies"
    - npm ci
    - echo "Lint source code with ESLint"
    - npm run lint

prettier:
  image: node:14.17.0-alpine
  stage: lint
  script:
    - echo "Install dependencies"
    - npm ci
    - echo "Format source code with Prettier"
    - npm run format

deploy:
  stage: deploy
  image: ubuntu:latest
  script:
    - apt -qq update && apt upgrade -qqy openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | > ~/.ssh/known_hosts
    # - scp -r $PWD deploy@ec2-3-127-197-161.eu-central-1.compute.amazonaws.com:~/social-network
    - rsync -a --progress --human-readable --delete --exclude-from '.gitignore' --exclude .gitignore --exclude .git
      . deploy@ec2-3-127-197-161.eu-central-1.compute.amazonaws.com:~/social-network
    - pm2 restart
