stages:
  - lint

cache:
  key:
    files:
      - package-lock.json
    paths:
      - .npm/

before-script:
  - npm ci --cache .npm --prefer-offline

eslint:
  image: node:14.17.0-alpine
  stage: lint
  script:
    - echo "Install dependencies"
    - npm ci
    - echo "Lint source code with ESLint"
    - npm run lint

prettier:
  image: node:14.17.0-alpine
  stage: lint
  script:
    - echo "Install dependencies"
    - npm ci
    - echo "Format source code with Prettier"
    - npm run format
