FROM node:14

WORKDIR /app

COPY ./package.json .

RUN npm i

COPY . .

EXPOSE 9000

ENTRYPOINT ["npx", "@compodoc/compodoc", "-p", "tsconfig.json", "-s", "-n", "EVSX social network API", "--includes", "./src/swagger"]
