name: eslint

# register actions on push and pull request into master
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  eslint:
    # environment for running
    runs-on: ubuntu-latest
    steps:
      # checkout repo via github actions
      - uses: actions/checkout@v2
      # scripts description
      - name: Install NVM
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      - name: Add nvm variable
        run: export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" --no-use
      - name: Reload terminal and instal Node.js
        env:
          NODE_VERSION: 14.17.0
        run: eval "[ -f .nvmrc ] && nvm install $NODE_VERSION
      - name: Install dependencies
        run: npm ci
      - name: Lint source code with ESLint
        run: npm run lint
